export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_REQUEST_SUCCESS = 'GET_USERS_REQUEST_SUCCESS';
export const GET_USERS_REQUEST_FAILED = 'GET_USERS_REQUEST_FAILED';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_REQUEST_SUCCESS = 'GET_USER_REQUEST_SUCCESS';
export const GET_USER_REQUEST_FAILED = 'GET_USER_REQUEST_FAILED';

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_REQUEST_SUCCESS = 'CREATE_USER_REQUEST_SUCCESS';
export const CREATE_USER_REQUEST_FAILED = 'CREATE_USER_REQUEST_FAILED';

export const EDIT_USER_REQUEST = 'EDIT_USER_REQUEST';
export const EDIT_USER_REQUEST_SUCCESS = 'EDIT_USER_REQUEST_SUCCESS';
export const EDIT_USER_REQUEST_FAILED = 'EDIT_USER_REQUEST_FAILED';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_REQUEST_SUCCESS = 'DELETE_USER_REQUEST_SUCCESS';
export const DELETE_USER_REQUEST_FAILED = 'DELETE_USER_REQUEST_FAILED';